### ISSUE TITLE
关于无法使用银行的bug(用中文发真的好吗)

### ISSUE THREAD

**Issue by D3it7i** [Him188/Money#2]
银行功能现在在最新的nukkit1.2.10上只能存款.取款显示成功却没有到账.是不是我的atm机有错误.请修复这个.谢谢

**Comment by Him188** [comment]
.......atm...是什么鬼woc2333333

**Comment by D3it7i** [comment]
2333.

**Comment by Him188** [comment]
en..刚刚看了代码，有个小问题，但ATM还是没问题的，它不会吞掉你的钱并骗你取出成功了。它只会在告诉你取出失败的时候随心情吞掉一部分钱。
另外ATM只支持货币1，存取都是货币1，你放货币2进去他会识别成假币的。

**Comment by D3it7i** [comment]
不过我想说的是.我取出了钱.提示成功.但是钱并没有取出.查询一下我的钱和银行的钱.并没有变化

**Comment by D3it7i** [comment]
并且我特意把其他插件删除掉来测试这个东西

**Comment by Him188** [comment]
看看语言文件，代码似乎并没有什么问题

**Comment by Him188** [comment]
失败会发failed, 成功会suceess. 只有reduceBank和addMony都成功，才会发给你success

**Comment by D3it7i** [comment]
我去尝试删掉插件的配置再尝试

**Comment by D3it7i** [comment]
我是说是的.这个bug在默认配置中有效. 请看图片:https://s1.ax1x.com/2018/02/11/9G3lZ9.png

**Comment by Him188** [comment]
唔..已列入TODO，这几天抽时间看看吧

**Comment by Him188** [comment]
我来修了...我似乎忘掉了这个事情= =

**Comment by Him188** [comment]
fixed
