### ISSUE TITLE
在1.5版本的核心中无法使用

### ISSUE THREAD

**Issue by BaicaiBear** [Him188/Money#3]
如题，设置商店后提示创建成功但是木牌内容不变，并且更换生存点击没有任何反应

**Comment by Him188** [comment]
issue位置错了..商店没时间更新了, 可以用 [MenuGUI](https://github.com/SayHellos/MenuGUI) 替代

**Comment by BaicaiBear** [comment]
位置错了不要紧...我在哪里可以下载到打包过的MenuGUI?

**Comment by Him188** [comment]
不知道...自己编译一下吧，
