### ISSUE TITLE
How to launch EconomyAPI based plugins with money plugin

### ISSUE THREAD

**Issue by CrystalRays** [Him188/Money#4]
I see in the new readme.md that it adapted to EconomyAPI.
So I put EconomyShop & EconomySell plugins with Money plugin without economy plugins.
But they report they can't launch alone. 
Help please，thanks.

**Comment by Him188** [comment]
Emm.. sorry,  I wrote the readme, but i haven't made the Adapter now... It is shceduled in today(Chinese time).

**Comment by Him188** [comment]
Ok, i have finished in plugin. And i sent an e-mail to onebone, if he(they) accept this, i will publish the adpater.

**Comment by Him188** [comment]
You can get adapters in releases page.

**Comment by CrystalRays** [comment]
Sorry, still the same error.

**Comment by CrystalRays** [comment]
the is the log:
icystal@VM-0-12-debian:~/Public/Nukkit$ java -jar nukkit.jar
Using log level 'INFO'
16:11:55 [INFO] Loading nukkit.yml...
16:11:55 [INFO] Loading server properties...
16:11:55 [INFO] 将 中文(简体) (chs) 设定为基本语言
16:11:55 [INFO] 正在启动支持 Minecraft: PE v1.5 版本的服务器
16:11:55 [INFO] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
16:11:55 [INFO] 正在启动服务器在 0.0.0.0:19132
16:11:55 [INFO] 此服务器正在运行 Nukkit 1.0dev 版本 "蘋果(Apple)派(Pie)" (API 1.0.6)
16:11:55 [INFO] Nukkit 根据 LGPL 许可发行
16:11:56 [INFO] Loading recipes...
16:11:56 [INFO] Loaded 954 recipes.
16:11:56 [INFO] Successfully loaded 0 resource packs
16:11:56 [INFO] 读取中... Mr_Popup v1.3.9
16:11:56 [CRITICAL] 无法读取插件 'EconomyShop'：本插件无法单独使用
16:11:56 [INFO] 读取中... WildPlugin v1.0
16:11:56 [INFO] 读取中... Wayback v1.0-SNAPSHOT
16:11:56 [CRITICAL] 无法读取插件 'EconomySell'：本插件无法单独使用
16:11:56 [INFO] 读取中... LockIt v2.0
16:11:56 [INFO] 读取中... EssentialsNK v1.1.0
16:11:56 [INFO] 读取中... SignsEditor v1.0.0
16:11:57 [INFO] 读取中... MoeDB v2.0.0
16:11:57 [INFO] 读取中... Unofficial_Nukkit_Patch vnull
16:11:57 [INFO] 读取中... SlashConsole v0.0.1
16:11:57 [INFO] 读取中... BetterSpawnProtection v0.0.1
16:11:57 [CRITICAL] 无法读取插件 'ASkyBlock'：本插件无法单独使用
16:11:57 [INFO] 读取中... MyOP v1.0.0
16:11:57 [INFO] 读取中... RsFunction v1.0.2
16:11:57 [INFO] 读取中... Money v3.2.1
16:11:57 [CRITICAL] 无法读取插件 'EconomyShop'：本插件无法单独使用
16:11:57 [INFO] 读取中... RsAuto v1.3.8
16:11:57 [CRITICAL] 无法读取插件 'EconomySell'：本插件无法单独使用
16:11:57 [CRITICAL] 无法读取插件 'ASkyBlock'：本插件无法单独使用
16:11:57 [CRITICAL] 无法读取插件 'EconomyShop'：本插件无法单独使用
16:11:57 [CRITICAL] 无法读取插件 'EconomySell'：本插件无法单独使用
16:11:57 [CRITICAL] 无法读取插件 'ASkyBlock'：本插件无法单独使用
16:11:57 [INFO] 读取中... Holograms v2.3
16:11:57 [INFO] Epoll is available. EpollEventLoop will be used.
16:11:57 [CRITICAL] 无法读取插件 'EconomyShop'：本插件无法单独使用
16:11:57 [CRITICAL] 无法读取插件 'EconomySell'：本插件无法单独使用
16:11:57 [CRITICAL] 无法读取插件 'ASkyBlock'：本插件无法单独使用
16:11:57 [CRITICAL] 无法读取插件 'EconomyShop'：检测出循环依赖
16:11:57 [CRITICAL] 无法读取插件 'EconomySell'：检测出循环依赖
16:11:57 [CRITICAL] 无法读取插件 'ASkyBlock'：检测出循环依赖
16:11:57 [INFO] 开启中... LockIt v2.0
16:11:57 [INFO] 开启中... MoeDB v2.0.0
16:11:57 [INFO] 开启中... RsFunction v1.0.2
16:11:57 [INFO] [RsFunction] You will use :zh
16:11:57 [INFO] 开启中... Holograms v2.3
16:11:57 [INFO] 准备地图中... "world"
16:11:57 [INFO] 准备地图中... "nether"
16:11:57 [INFO] 开启中... Mr_Popup v1.3.9
16:11:57 [INFO] [Mr_Popup] 检测到Money插件，插件正开启显示金钱和点券功能
16:11:57 [INFO] [Mr_Popup] 没有检测到Mr_Love插件，插件将不能显示情侣相关信息
16:11:57 [ALERT] java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
        at cn.nukkit.Server.enablePlugin(Server.java:678)
        at cn.nukkit.Server.enablePlugins(Server.java:667)
        at cn.nukkit.Server.<init>(Server.java:509)
        at cn.nukkit.Nukkit.main(Nukkit.java:105)
Caused by: java.lang.NullPointerException
        at cn.nukkit.command.data.CommandParameter.fromString(CommandParameter.java:75)
        at cn.nukkit.command.data.CommandParameter.<init>(CommandParameter.java:35)
        at top.ascserver.mr_popup.command.PopupCommand.<init>(PopupCommand.java:18)
        at top.ascserver.mr_popup.Timers.onEnable(Timers.java:40)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
        ... 4 more

16:11:57 [INFO] 关闭中... Mr_Popup v1.3.9
16:11:57 [INFO] 开启中... WildPlugin v1.0
16:11:57 [INFO] [WildPlugin] [Wild] enable
16:11:57 [INFO] 开启中... Wayback v1.0-SNAPSHOT
16:11:57 [INFO] [Wayback]
16:11:57 [INFO] [Wayback]                                              __
16:11:57 [INFO] [Wayback]   _   __   _              __                / /
16:11:57 [INFO] [Wayback]  / |/ | |/ / __   __  __ / /    __   _____ / /___
16:11:57 [INFO] [Wayback]  | | /| | // _ | / / / // /__ / _ | / ___// /_ _/
16:11:57 [INFO] [Wayback]  |  / |  // __ |/ /_/ // /_ // __ |/ /__ / /\
16:11:57 [INFO] [Wayback]  |_/  |_//_/  |/\__/ / \__ //_/  |/\___// /\ \
16:11:57 [INFO] [Wayback]                   / /                  / /  \/
16:11:57 [INFO] [Wayback]                __/ /                   |/
16:11:57 [INFO] [Wayback]               /__ /     version 1.0-SNAPSHOT
16:11:57 [INFO] [Wayback]
16:11:57 [INFO] 开启中... EssentialsNK v1.1.0
16:11:57 [INFO] [EssentialsNK] EssentialsNK 加载成功！
16:11:57 [INFO] 开启中... SignsEditor v1.0.0
16:11:57 [INFO] 开启中... Unofficial_Nukkit_Patch vnull
16:11:57 [WARNING] [Unofficial_Nukkit_Patch] Unofficial Nukkit Patch enabled!Author:Shanwer
16:11:57 [INFO] 开启中... SlashConsole v0.0.1
16:11:57 [INFO] 开启中... BetterSpawnProtection v0.0.1
16:11:57 [INFO] 开启中... MyOP v1.0.0
16:11:57 [INFO] [MyOP] |NK MyOP Loading.. by Knight|
16:11:57 [INFO] 开启中... Money v3.2.1
16:11:57 [INFO] 开启中... RsAuto v1.3.8
16:11:57 [INFO] [RsAuto] RsAuto is Loaded
16:11:57 [INFO] 启动 GS4 状态监听器
16:11:57 [INFO] 将 Query 端口设定为 19132
16:11:57 [INFO] Query 运行在 0.0.0.0:19132
16:11:57 [INFO] 默认的游戏模式为：生存模式
16:11:57 [INFO] 启动完成 (2.891s)！如需帮助，请输入 "help" 或 "?"
