### ISSUE TITLE
The plugins seems not working...

### ISSUE THREAD

**Issue by CrystalRays** [Him188/Money#7]
Sorry for open 3 issues in one day...

No matter how I type the command in the game or in the console, there isn't any output...

such as:
17:35:13 [INFO] CrystalRays[/39.172.175.140:27098] 登入游戏，实体 ID 为 1，坐标位于 (world, 130.7344, 73.0, 129.7512)
17:35:14 [INFO] CrystalRays 加入了游戏
> /givecoin crystalrays 100
> stop
17:35:50 [INFO] [CONSOLE: 正在关闭服务器]

**Comment by Him188** [comment]
sorry, i will fix them tomorrow, im so tired today..

**Comment by CrystalRays** [comment]
Thanks
